name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build Application
      run: mvn clean package -DskipTests
      
    - name: Build Docker Image
      run: |
        docker build -t bookmyshow-backend .
        docker build -t bookmyshow-frontend ./frontend
        
    - name: Run Security Scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD:/tmp/.cache/ aquasec/trivy:latest image \
          --exit-code 0 --no-progress --format table \
          bookmyshow-backend
          
    - name: Deploy to Staging
      run: |
        echo "🚀 Deploying to staging environment..."
        # Add your deployment commands here
        
    - name: Run Smoke Tests
      run: |
        echo "🧪 Running smoke tests..."
        # Add smoke test commands here
        
    - name: Notify Deployment
      uses: actions/github-script@v6
      with:
        script: |
          const commit = context.sha.substring(0, 7);
          const message = `🚀 **Deployment Successful!**\n\n` +
            `**Commit:** ${commit}\n` +
            `**Environment:** Production\n` +
            `**Time:** ${new Date().toISOString()}\n\n` +
            `✅ All checks passed and application is live!`;
            
          // You can send this to Slack, Discord, or create an issue
          console.log(message);